// src/Separators/Separator.tsx
import React from 'react';
import { Direction, Position } from 'Crossword/Crossword.types';

import Line from './Line';

type Props = {
  direction: Direction;
  position: Position;
  separator: string;
  locations: number[];
};

const Separator = ({ direction, position, separator, locations }: Props) => {
  switch (separator) {
    case ',':
      return (
        <Line position={position} locations={locations} direction={direction} />
      );
    default:
      return null;
  }
};

export default Separator;

// src/lib/components/cells/Separator.svelte
<script lang="ts">
	import Line from '$lib/components/Line.svelte';
	import type { Direction, Position } from '$lib/types';

	type Props = {
		direction: Direction;
		position: Position;
		separator: string;
		locations: number[];
		id: string;
	};

	const { direction, position, separator, locations, id }: Props = $props();
</script>

{#if separator === ','}
	{#each locations as location (`${id}-${location}`)}
		<Line {position} {location} {direction} />
	{/each}
	))}
{/if}
