// src/Separators/Separators.tsx
import React from 'react';
import { SeparatorType } from 'Crossword/Crossword.types';
import Separator from './Separator';

type Props = {
  separators?: SeparatorType[];
};

const Separators = ({ separators }: Props) => {
  if (!separators || separators.length === 0) {
    return null;
  }
  return (
    <>
      {separators.map(({ direction, position, separator, locations, id }) => (
        <Separator
          key={`${id}-${separator}`}
          direction={direction}
          position={position}
          separator={separator}
          locations={locations}
        />
      ))}
    </>
  );
};

export default Separators;

// src/lib/components/cells/Separators.svelte
<script lang="ts">
	import Separator from '$lib/components/cells/Separator.svelte';
	import type { SeparatorType } from '$lib/types';

	type Props = {
		separators?: SeparatorType[];
	};

	const { separators }: Props = $props();
</script>

{#if separators?.length}
	{#each separators as { direction, position, separator, locations, id } (`${id}-${separator}`)}
		<Separator {id} {direction} {position} {separator} {locations} />}}
	{/each}
{/if}
